---
  el:
    hosts:
      centos7:
        ansible_connection: docker
        ansible_python_interpreter: /opt/rh/rh-python38/root/usr/bin/python3.8
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker